

public enum LogEnum {
	MONEY_DUP_PRIZE(1001, "副本奖励"), MONEY_SWEEP_DUP_PRIZE(1002, "扫荡副本奖励"), MONEY_TASK_PRIZE(
			1003, "任务获得"), MONEY_DUP_STORY(1004, "进入支线剧情副本"), MONEY_RESTORE_EQUIP(
			1005, "修理装备消耗金币"), MONEY_ASSIST_REWARD(1006, "协助精炼奖励金币"), MONEY_ASSIST_COST(
			1007, "协助精炼消耗金币"), MONEY_TYPE_REMOVE_QH(1008, "强化装备扣除"), MONEY_TYPE_GET_SALE_GOODS(
			1009, "出售物品到商店"), MONEY_CONCISE_EQUIP_COST(1010, "精炼装备消耗"), MONEY_TYPE_REMOVE_ALCHEMY(
			1011, "炼金花费金币"), MONEY_TYPE_REMOVE_HG(1012, "商店回购物品消耗金币"), MONEY_TYPE_REMOVE_BUYGOODS(
			1013, "商店购买物品"), MONEY_TYPE_BUY_MNY_REWARD(1014, "开启巨龙宝藏奖励金币"), MONEY_TYPE_REF_GEM_ATRIB(
			1015, "刷新宝石属性值金币消耗"), MONEY_TYPE_COMBINE_COST(1016, "普通合成消耗金币"), MONEY_TYPE_COMBINE_FMU_COST(
			1017, "高级合成消耗金币"), MONEY_TYPE_RESOLVE_COST(1018, "分解装备消耗金币"), MONEY_TYPE_BUY_TITLE_AGING(
			1019, "购买成就称号消耗金币"), PP_TASK(2001, "任务奖励"), PP_BUY_MNY_VIP_PP_COST(
			2002, "开启巨龙宝藏声望消耗"), PP_ALCHEMY_CHANGE_MC_PART_TO_MC(2003,
			"符文兑换声望消耗"), TREASURE_SPEED_STAR_TASK(4001, "消耗钻石加速完成星级任务"), TREASURE_DUP_STORY(
			4002, "进入支线剧情副本"), TREASURE_OPEN_GEM_HOLE(4003, "装备宝石开孔"), TREASURE_COMBINE(
			4004, "使用元宝补充合成材料"), TREASURE_OVERRIDE_ADD_GEM(4005, "覆盖原来的宝石"), TREASURE_BUY_MNY_TRE_COST(
			4006, "开启巨龙宝藏钻石消耗"), TREASURE_INCREASE_DEPOT_CAPACITY(4007,
			"开启普通背包格子消耗钻石"), TREASURE_AUCTION_PUTAWAY_SHOW_PRICE(4008,
			"玩家拍卖行上架物品扣除展示费"), TREASURE_AUCTION_BUY_GOODS(4009, "玩家拍卖行购买物品消耗钻石"), TREASURE_REF_GEM_ATRIB(
			4010, "刷新宝石属性值钻石消耗"), TREASURE_BUY_ELITE_DUP_COUNT(4011,
			"购买精英副本的次数"), TREASURE_TRE_COMBINE_COST(4012, "单次合成消耗钻石"), TREASURE_TRE_QUICK_COMBINE_COST(
			4013, "多次合成消耗钻石"), TREASURE_TRE_LADDER_REMATCH(4014, "重新撮合对手"), TREASURE_TRE_VIP_PRIZE(
			4015, "领取VIP钻石奖励"), TREASURE_TRE_VIP_BUY_ACTIVITY_COUNT(4016,
			"购买活动次数"), TREASURE_DUP_SUMMON_COST(4017, "召唤小伙伴扣费"), TREASURE_SOULSHOP_ARTIFICIAL_REFRESH(
			4018, "灵魂商店玩家刷新操作扣费"), TREASURE_SOULSHOP_BUY_GOODS(4019,
			"灵魂商店玩家购买消耗钻石"), MC_TASK(5001, "任务奖励"), PLAYER_STORY_DUP(6001,
			"进入支线剧情扣除项"), PLAYER_DUP_PRIZE(6002, "副本奖励"), PLAYER_BUY_AP(6003,
			"购买体力"), PLAYER_ONCE_RECOVER_AP(6004, "每半小时恢复体力"), PLAYER_BUY_MNY_NUM(
			6005, "开启巨龙宝藏使用次数"), PLAYER_ALCHEMY_RUNEF_USE_COUNT(6006,
			"符文炼金消耗符文炉使用次数"), PLAYER_LV_SECTION_PRIZE(6007, "玩家升级宝箱奖励"), DUP_SWEEP_DUP_PRIZE(
			7001, "扫荡副本"), DUP_PASS_PRIZE(7002, "通关副本"), DUP_ENTER_DUP(7003,
			"进入副本"), DUP_ENTER_STORY_DUP(7004, "进入支线剧情副本"), DUP_REVIVE(7005,
			"副本立即复活"), SCENE_ABYSS_BOSS_BOX(7006, "场景深渊boss奖励"), SCENE_ABYSS_DEFEND_BOX(
			7007, "深渊守卫"), SCENE_REVIVE_BY_TREASURE_IN_FS(7008, "战斗中复活"), SCENE_DUP_GET_CHAPTER_BOX_ID(
			7009, "领取副本章节宝箱"), SCENE_DUP_COST_DRAW_BOX(7010, "付费领取副本宝箱"), SCENE_ABYSS_BOSS_COST_DRAW_BOX(
			7011, "付费领取深渊boss宝箱"), SCENE_TOWN_COST_BUFF(7012, "付费获取随机buff"), SCENE_TOWN_COST_CHANGE_GRADE(
			7013, "付费钻石改变高塔难度等级"), SCENE_TOWN_PASS_SCENE(7014, "高塔通关"), TASK_PRIZE(
			8001, "任务奖励"), TASK_FRESH_STAR_TASKS(8002, "刷新星级任务"), TASK_ACCEPT_BOX(
			8003, "接受任务获取宝箱"), DAILY_TARGET_PRIZE(9001, "每日目标奖励"), DAILY_TARGET_POINT_PRIZE(
			9002, "每日目标活跃积分奖励"), FORGEN_EXP_RESOLVE(10001, "单个装备分解获得淬炼精华"), FORGEN_EXP_ALL_RESOLVE(
			10002, "多个装备分解获得淬炼精华"), FORGEN_EXP_REFINE_DEPOT_EQUIP(10003,
			"强化背包中的装备消耗淬炼精华"), FORGEN_EXP_REFINE_HERO_EQUIP(10004,
			"强化人物身上的装备消耗淬炼精华"), FORGEN_EXP_CAMP_BATTLE(10005, "决斗场奖励"), FORGEN_EXP_SUMMON_COUNT(
			10006, "召唤次数奖励"), SCENE_PVP_GENERAL_TEAM(11001, "将军战团队奖励"), SCENE_PVP_GENERAL_PERSONAL(
			11002, "将军战个人奖励"), GOODS_TYPE_REMOVE_BY_PLAYER(12001, "玩家主动丢弃物品"), GOODS_TYPE_GET_MC_BY_ALCHEMY(
			12002, "炼金获得符文(放在炼金桌上)"), GOODS_TYPE_USE_GOODS_COST(12003, "使用物品扣除"), GOODS_TYPE_COMBINE_GOODS_COST(
			12004, "合成物品扣除"), GOODS_TYPE_COMBINE_GOODS_RESULT(12005,
			"合成物品的生成的物品"), GOODS_TYPE_USE_GOODS_RESULT(12006, "使用物品生成的物品"), GOODS_TYPE_SELL_GOODS_REMOVE(
			12007, "卖出的物品"), GOODS_TYPE_RECAST_EQUIP_COST(12008, "精练装备消耗物品"), GOODS_TYPE_CLEAR_ALCHEMY_TABLE_TO_MCEXP(
			12009, "一键转符文经验"), GOODS_TYPE_CHANGE_POINT_MC_TO_MCEXP(12011,
			"指定位置转符文经验"), GOODS_TYPE_EXCHANGE_MC_FROM_MCEXP(12012,
			"将符文碎片转换为符文经验"), GOODS_TYPE_DUP_PRIZE(12014, "副本奖励"), GOODS_TYPE_TASK_PRIZE(
			12015, "任务奖励"), GOODS_DUP_STORY(12016, "进入支线剧情副本"), GOODS_TYPE_BUY_SELL_BACK_GOODS(
			12017, "回购物品"), GOODS_TYPE_EXCHANGE_GOODS_COST(12018,
			"使用物品进行交换时的扣除"), GOODS_TYPE_BUY_GOODS_RESULT(12019, "购买的物品"), GOODS_TYPE_BUY_MNY_VIP_REWARD_GOODS(
			12020, "开启巨龙宝藏额外奖励物品"), GOODS_TYPE_SUBMIT_COLLECT_MATARIAL_TASK(
			12021, "完成搜集材料任务扣除物品"), GOODS_TYPE_EX(12022, "完成搜集材料任务扣除物品"), GOODS_TYPE_HERO_EXCHANGE(
			12023, "兑换英雄"), GOODS_TYPE_CHANGE_HERO_EXP(12024, "兑换英雄经验"), GOODS_TYPE_TAKE_PIECE(
			12025, "抽取碎片"), GOODS_TYPE_GET_PIECE_BY_TABLE(12026, "将碎片从展示处放入背包"), GOODS_TYPE_AUCTION_AUCTION_PUTAWAY(
			12027, "拍卖行上架商品消耗物品"), GOODS_TYPE_RESOLVE_EQUIPMENT_REWARD_STONE(
			12028, "分解装备获得经验石"), GOODS_TYPE_RESOLVE_EQUIPMENT_REMOVE_EQUIPMENT(
			12029, "分解装备销毁装备"), GOODS_TYPE_REFINE_EQUIP_COST_GOODS(12030,
			"强化装备消耗材料"), GOODS_TYPE_DE_EQUIP_COST_GOODS(12031, "升阶装备消耗材料"), GOODS_TYPE_DE_DEPOT_EQUIP_RESULT(
			12032, "装备升阶生成新的装备"), GOODS_TYPE_DE_DEPOT_EQUIP_REMOVE(12033,
			"装备升阶删除旧的装备"), GOODS_TYPE_CC_RESET_EQUIP_COST(12034,
			"装备普通回退精炼等级消耗物品"), GOODS_TYPE_CC_RESET_X_EQUIP_COST(12035,
			"装备高级回退精炼等级消耗物品"), GOODS_TYPE_CAMP_PVP(12036, "角斗场奖励"), GOODS_TYPE_NEWBIE_PACKS(
			12037, "新手礼包"), GOODS_TYPE_LADDER_RANKING(12038, "天梯排名"), GOODS_TYPE_LOGIN_TARGET_ONLINE(
			12039, "登录目标在线奖励"), GOODS_TYPE_LOGIN_TARGET_CONTINUOUS_LOGIN(12040,
			"登录目标连续日登录奖励"), GOODS_TYPE_RESOLVE_EQUIPMENT_REWARD_EQUIPMENT(
			12041, "分解装备铸造过的装备补偿材料"), GOODS_TYPE_FORGEEQUIP_OBLATION_GOODS_COST(
			12042, "铸造装备时扣除祭品装备"), GOODS_TYPE_COMBINE_REWARD_GOODS(12043,
			"合成额外奖励物品"), GOODS_TYPE_ESSENCE_EXTRACT_REWARD_GOODS(12044,
			"技能精华抽取奖励"), GOODS_TYPE_TASK_COST_RUNE_GOODS(12045, "任务消耗符文"), GOODS_TYPE_SOULSHOP_BUY_GOODS(
			12046, "灵魂商店购买物品获得"), GOODS_TYPE_COMBINE_GOODS_PIECE_COST_GOODS(
			12047, "物品碎片合成消耗"), GOODS_TYPE_COMBINE_GOODS_PIECE_ADD_GOODS(12048,
			"物品碎片合成消耗"), GOODS_TYPE_GET_GOODS_FROM_TASK(12049, "任务物品奖励"), GOODS_TYPE_DE_GOODS_STUDYSKILL(
			12050, "学习技能扣除"), GOODS_TYPE_EQUIP_RESOLVE_ONE(12051, "装备分解一个"), GOODS_TYPE_EQUIP_RESOLVE_ALL(
			12052, "装备分解所有"), GOODS_TYPE_EQUIP_REFINE_DEPOT_EQUIP(12053,
			"装备强化背包装备"), GOODS_TYPE_EQUIP_REFINE_HERO_EQUIP(12054, "装备强化英雄装备"), GOODS_TYPE_EQUIP_CONCISE_DEPOT_EQUIP(
			12055, "装备精炼背包装备"), GOODS_TYPE_EQUIP_CONCISE_HERO_EQUIP(12056,
			"装备精炼英雄装备"), GOODS_TYPE_EQUIP_CC_RESET_DEPOT_EQUIP(12057,
			"背包中的装备精炼回退"), GOODS_TYPE_EQUIP_CC_RESET_HERO_EQUIP(12058,
			"英雄身上的装备精炼回退"), GOODS_TYPE_EQUIP_EQUIP_MC(12059, "装备符文"), GOODS_TYPE_EQUIP_UN_EQUIP_MC(
			12060, "装备取下符文"), GOODS_TYPE_EQUIP_UPGRADE_DEPOT_MC(12061,
			"强化背包中的符文"), GOODS_TYPE_EQUIP_UPGRADE_HERO_MC(12062, "强化背包中的符文"), GOODS_TYPE_EQUIP_COMBINE(
			12063, "装备普通合成"), GOODS_TYPE_EQUIP_COMBINE_FORMULA(12064,
			"装备合成需消耗摸具"), GOODS_TYPE_EQUIP_QUICK_COMBINE(12065, "装备普通五连合成"), GOODS_TYPE_EQUIP_QUICK_COMBINE_FORMULA(
			12066, "装备五连高级合成"), GOODS_TYPE_EQUIP_FORGE_DEPOT_EQUIP(12067,
			"背包中的装备铸造"), GOODS_TYPE_EQUIP_FORGE_HERO_EQUIP(12068, "角色身上的装备铸造"), GOODS_TYPE_EQUIP_TRE_COMBINE(
			12069, "/钻石单次合成"), GOODS_TYPE_EQUIP_TRE_QUICK_COMBINE(12070,
			"钻石多次合成"), GOODS_TYPE_EQUIP_DEGREE_DEPOT_EQUIP(12071, "背包中的装备升星"), GOODS_TYPE_EQUIP_DEGREE_HERO_EQUIP(
			12072, "英雄身上的装备升星"), GOODS_TYPE_EQUIP_FREE_TRE_COMBINE(12073,
			"免费钻石合成"), GOODS_TYPE_ESSENCE_EXTRACT(12074, "抽取技能精华"), GOODS_TYPE_ESSENCE_EQUIP_ESSENCE(
			12075, "装备技能精华"), GOODS_TYPE_ESSENCE_UN_EQUIP_ESSENCE(12076,
			"取下技能精华"), GOODS_TYPE_ESSENCE_RESOLVE(12077, "分解技能精华"), GOODS_TYPE_GOODS_ADD_GOODS(
			12078, "增加物品"), GOODS_TYPE_GOODS_USE_GOODS(12079, "使用道具"), GOODS_TYPE_GOODS_SELL_GOODS_TO_SHOP(
			12080, "卖出道具"), GOODS_TYPE_GOODS_EQUIP(12081, "穿戴装备"), GOODS_TYPE_GOODS_UN_EQUIP(
			12082, "卸下装备"), GOODS_TYPE_GOODS_RESTORE_DEPOT_EQUIP(12083,
			"背包中的装备修复"), GOODS_TYPE_GOODS_RESTORE_HERO_EQUIP(12084, "英雄身上的装备修复"), GOODS_TYPE_GOODS_RESTORE_ALL_EQUIP(
			12085, "修复装备在身上的所有装备"), GOODS_TYPE_GOODS_BUY_GOODS_FROM_SHOP(12086,
			"从商店购买物品"), GOODS_TYPE_GOODS_BUY_BACKUP_GOODS(12087, "从回购桌面购回卖出物品"), GOODS_TYPE_GOODS_OPEN_GRAGON_TREASURE(
			12088, "开启巨龙宝藏"), MC_Type_Get_AllTableGoods2MCExp(13001,
			"桌面所有符文兑换成经验"), MC_Type_Remove_Upgrade(13002, "升级符文"), MC_Type_Get_Alchemy_McPart(
			13003, "炼金获得符文碎片"), MC_Type_Get_ChangePo(13004, "桌面单个符文兑换成经验"), MC_Type_Remove_ChangeMCPartToMC(
			13005, "符文碎片兑换符文消耗"), MC_TYPE_REMOVE_ESSENCE_EXTRACT(13006,
			"技能精华抽取消耗符文碎片"), MC_Type_Get_Resolve_Essence_McPart(13007,
			"分解技能精华获得符文碎片"), MC_Type_Remove_Resolve_Essence(13008, "分解删除技能精华"), MC_TYPE_QUICK_ALCHEMY(
			13009, "快速炼金"), MC_TYPE_COLLECT_POINT_ITEM_ON_ALCHEMY_TABLE(13010,
			"从炼金桌面收集一个符文"), VIP_GET_EXPERIENCE(14001, "体验卡获取VIP"), VIP_GET_BUY(
			14002, "购买VIP"), VIP_DELETE_EXPIRE(14003, "VIP过期"), VIP_GET_UPGRADE(
			14004, "VIP升级"), MAIL_PICK_UP(15001, "从邮件附件从获得");

	public int value;
	public String name;

	private LogEnum(int value, String name) {
		this.value = value;
		this.name = name;
	}

	public static String gettypeByvalue(int code) {
		for (LogEnum logEnum : LogEnum.values()) {
			if (code == logEnum.getValue()) {
				return logEnum.getName();
			}
		}
		return "";
	}

	public int getValue() {
		return value;
	}

	public void setValue(int value) {
		this.value = value;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
